name: web_socket_support_example
description: Demonstrates how to use the web_socket_support plugin.
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  web_socket_support:
    path: ../

  provider: ^6.0.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
