name: web_socket_support

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job configuration for the web_socket_support flutter build (Mobile Implementation Package)
  mobile_implementation_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up JDK 17, Android Gradle plugin requires Java 17 to run.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: java -version
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'dev'

      # Download all Flutter packages the web_socket_support depends on
      - name: Download dependencies
        run: flutter pub get

      # Run Flutter Format to ensure formatting is valid
      - name: Run Dart Format
        run: dart format --set-exit-if-changed lib

      # Run Flutter Analyzer
      - name: Run Flutter Analyzer
        run: flutter analyze

      # Run all unit-tests with code coverage
      - name: Run unit tests
        run: flutter test --coverage

      # Build Android version of the example app
      - name: Run Android build
        run: flutter build apk --release
        working-directory: ./example

      # Build iOS version of the example app
      # - name: Run iOS build
      #  run: flutter build ios --release --no-codesign
      #  working-directory: ./example

      # Upload code coverage information for flutter
      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info,./example/build/web_socket_support/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          name: WebSocketSupport (Mobile Implementation) # optional
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # required
